Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('menu','a01','�Ϲ�',null,null,null,null);
Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('menu','a02','Q&A',null,null,null,null);
Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('menu','a03','�͸�',null,null,null,null);
Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('menu','a04','����',null,null,null,null);
Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('phone','1','010',null,null,null,null);
Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('phone','2','011',null,null,null,null);
Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('phone','3','016',null,null,null,null);
Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('phone','4','017',null,null,null,null);
Insert into COM_CODE (CODE_TYPE,CODE_ID,CODE_NAME,CREATOR,CREATE_TIME,MODIFIER,MODIFIED_TIME) values ('phone','5','019',null,null,null,null);